---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-cluster-{{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
spec:
  template:
    metadata:
      name: create-cluster-{{ .Release.Name }}
    spec:
      serviceAccountName: "{{ .Values.serviceAccount }}"
      restartPolicy: Never
      volumes:
        {{- include "credential-volumes" . | nindent 8 }}
      initContainers:
        {{- include "aws-sts-init-container" . | nindent 8 }}
      containers:
        - name: hypershift
          image: quay.io/hypershift/hypershift-operator:{{ .Values.hypershiftImageTag }}
          volumeMounts:
            - name: sts
              mountPath: /sts
            - name: secret
              mountPath: /secret
          args:
            - create
            - cluster
            - aws
            - --name
            - "{{ .Release.Name }}"
            - --infra-id
            - "{{ .Release.Name | trunc -12 }}"
            - --namespace
            - "{{ .Release.Namespace }}"
            - --sts-creds
            - /sts/token.json
            - --role-arn
            - "{{ .Values.hypershiftRoleArn }}"
            - --pull-secret
            - /secret/pull-secret
            - --base-domain
            - "{{ .Values.baseDomain }}"
            - --region
            - "{{ .Values.region }}"
            - --multi-arch
            - --arch
            {{- if hasPrefix "m6g." .Values.instanceType }}
            - arm64
            {{- else }}
            - amd64
            {{- end }}
            - --instance-type
            - "{{ .Values.instanceType }}"
            - --node-pool-replicas
            - "{{ .Values.nodePoolReplicas }}"
            - --release-image
            - quay.io/openshift-release-dev/ocp-release:{{ .Values.version }}-multi
            - --control-plane-availability-policy
            - SingleReplica
            - --infra-availability-policy
            - SingleReplica
            - --annotations
            - argocd.argoproj.io/tracking-id={{ .Release.Name }}:hypershift.openshift.io/HostedCluster:{{ .Release.Namespace }}/{{ .Release.Name }}
            - --annotations
            - argocd.argoproj.io/compare-options=IgnoreExtraneous
            - --annotations
            - argocd.argoproj.io/sync-options=Prune=false,Delete=false
            - --timeout
            - "{{ .Values.timeout }}"
            - --wait
