---
apiVersion: batch/v1
kind: Job
metadata:
  name: destroy-cluster-{{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      name: destroy-cluster-{{ .Release.Name }}
    spec:
      serviceAccountName: "{{ .Values.serviceAccount }}"
      restartPolicy: Never
      volumes:
        {{- include "credential-volumes" . | nindent 8 }}
      initContainers:
        {{- include "aws-sts-init-container" . | nindent 8 }}
      containers:
        - name: hypershift
          image: "{{ .Values.hypershiftImage }}"
          volumeMounts:
            - name: sts
              mountPath: /opt/hypershift/sts
          command:
            - hypershift
          args:
            - destroy
            - cluster
            - aws
            - --name
            - "{{ .Release.Name }}"
            - --infra-id
            - "{{ .Release.Name | trunc -12 }}"
            - --namespace
            - "{{ .Release.Namespace }}"
            - --sts-creds
            - /opt/hypershift/sts/token.json
            - --role-arn
            - "{{ .Values.hypershiftRoleArn }}"
            - --region
            - "{{ .Values.region }}"
            - --base-domain
            - "{{ .Values.baseDomain }}"
