# Default values for hypershift-aws-template.

hypershiftImageTag: "4.16"

instanceType: m5.large

nodePoolReplicas: 2

region: us-east-1

secret: hypershift

serviceAccount: cluster-provisioner

timeout: 20m
