# Default values for hypershift-aws-template.

hypershiftImage: quay.io/hypershift/hypershift-operator:latest

imageContentSources: ""

instanceType: m5.large

nodePoolReplicas: 2

pausePod:
  enabled: false
  priorityClass: pause-pod-priority
  image: registry.access.redhat.com/ubi8/pause:8.10-15.1739286914@sha256:6e1d6846e3f5af2fee1d4bd79c7424d124c61e7e505deb5ffbae08244c0d8071
  # Sizing based on the baseline resource consumption for a control plane:
  # https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/hosted_control_planes/preparing-to-deploy-hosted-control-planes#hcp-pod-limits_hcp-sizing-guidance
  cpu: "5"
  memory: 18Gi

region: us-east-1

# checkov:skip=CKV_SECRET_6:This is the name of a Secret, not its content
secret: hypershift

serviceAccount: cluster-provisioner

timeout: 20m
