# Default values for hypershift-aws-template.

hypershiftImage: quay.io/hypershift/hypershift-operator:latest

imageContentSources: ""

instanceType: m5.large

nodePoolReplicas: 2

region: us-east-1

# checkov:skip=CKV_SECRET_6:This is the name of a Secret, not its content
secret: hypershift

serviceAccount: cluster-provisioner

timeout: 20m
